# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- devdemo

pool:
  vmImage: ubuntu-latest

variables:
  projectName: 'tickets.mobile'
  ticketsFolder: '$(Build.SourcesDirectory)/src'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run deploy
  displayName: 'npm install and build'
  workingDirectory: '$(ticketsFolder)/$(projectName)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(ticketsFolder)/$(projectName)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    ArtifactName: "$(projectName)"
    publishLocation: "Container"
  displayName: "Publish artifacts"

